[tool.ruff]
lint.select = ["I001"]

[tool.isort]
profile = "black"
line_length = 88
known_third_party = ["flask", "requests", "sqlalchemy"]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true
