"""Initial migration

Revision ID: c59c13428508
Revises: 
Create Date: 2024-08-05 09:58:28.668035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c59c13428508'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iso_countires',
    sa.Column('iso_code', sa.String(length=3), nullable=False),
    sa.Column('names', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('iso_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('iso_countires')
    # ### end Alembic commands ###
